# -*- coding: utf-8 -*-
"""mudule_2_Complete the EDA with SQL- SQL(google colab).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6A1r8W-TOIf_vnfBGmkRbjh1P7CwrE6
"""

# 1️⃣ نصب کتابخانه‌ها
!pip install sqlalchemy pandas

# 2️⃣ وارد کردن کتابخانه‌ها
import pandas as pd
from sqlalchemy import create_engine
import sqlite3

# 3️⃣ بارگذاری CSV
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")

# 4️⃣ ساخت دیتابیس SQLite و جدول SPACEXTBL
engine = create_engine('sqlite:///spacex.db')
df.to_sql("SPACEXTBL", con=engine, if_exists='replace', index=False)

# 5️⃣  اتصال با sqlite3 برای اجرای SQL با Pandas
conn = sqlite3.connect("spacex.db")

#6.1 تمام سایت‌های منحصر به فرد
df1 = pd.read_sql("SELECT DISTINCT Launch_Site FROM SPACEXTBL", conn)
print(df1)
#تمام سایت‌های منحصر به فرد پرتاب

#6.2 رکوردهایی که Launch_Site با 'CCA' شروع می‌شوند
df2 = pd.read_sql("SELECT * FROM SPACEXTBL WHERE Launch_Site LIKE 'CCA%'", conn)
print(df2.head())
#سایت‌هایی که با 'CCA' شروع می‌شوند

#6.3 مجموع جرم محموله برای مشتری NASA (CRS)
df3 = pd.read_sql("SELECT SUM(PAYLOAD_MASS__KG_) AS total_mass_nasa FROM SPACEXTBL WHERE Customer = 'NASA (CRS)'", conn)
print(df3)
#مجموع جرم محموله برای NASA (CRS)

#6.4 میانگین جرم محموله برای بوستر F9 v1.1
df4 = pd.read_sql("SELECT AVG(PAYLOAD_MASS__KG_) AS avg_mass_f9v1_1 FROM SPACEXTBL WHERE Booster_Version = 'F9 v1.1'", conn)
print(df4)
#میانگین جرم محموله برای F9 v1.1

#6.5 اولین موفقیت فرود روی Ground Pad
df5 = pd.read_sql("SELECT MIN(Date) AS first_success_ground_pad FROM SPACEXTBL WHERE Landing_Outcome = 'Success (ground pad)'", conn)
print(df5)
#اولین موفقیت فرود روی Ground Pad

#6.6 بوسترهایی که موفق روی Drone Ship شدند و جرم بین 4000 تا 6000
df6 = pd.read_sql("""
SELECT Booster_Version
FROM SPACEXTBL
WHERE Landing_Outcome = 'Success (drone ship)'
  AND PAYLOAD_MASS__KG_ > 4000
  AND PAYLOAD_MASS__KG_ < 6000
""", conn)
print(df6)
#بوسترهایی که موفق روی Drone Ship شدند و جرم بین 4000 تا 6000:

#6.7 شمارش انواع Mission_Outcome
df7 = pd.read_sql("SELECT Mission_Outcome, COUNT(*) AS count FROM SPACEXTBL GROUP BY Mission_Outcome", conn)
print(df7)
#شمارش انواع Mission_Outcome:

#6.8 بیشترین جرم محموله و بوسترهایی که آن را حمل کرده‌اند
df8 = pd.read_sql("""
SELECT Booster_Version
FROM SPACEXTBL
WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTBL)
""", conn)
print(df8)
#بوسترهایی که بیشترین جرم محموله را حمل کرده‌اند

#6.9 رکوردهای سال 2015 با فرود ناموفق روی Drone Ship و شماره ماه
df9 = pd.read_sql("""
SELECT SUBSTR(Date,6,2) AS Month, Landing_Outcome, Booster_Version, Launch_Site
FROM SPACEXTBL
WHERE Date LIKE '2015%' AND Landing_Outcome = 'Failure (drone ship)'
""", conn)
print(df9.head())
#رکوردهای سال 2015 با فرود ناموفق روی Drone Ship و شماره ماه:")

#6.10 فیلتر رکوردها بین دو تاریخ و شمارش Landing_Outcome با رتبه‌بندی
df10 = pd.read_sql("""
SELECT Landing_Outcome, COUNT(*) AS Count
FROM SPACEXTBL
WHERE Date >= '2010-06-04' AND Date <= '2017-03-20'
GROUP BY Landing_Outcome
ORDER BY Count DESC
""", conn)
print(df10)
#شمارش Landing_Outcome بین دو تاریخ